### ISSUE TITLE
gulp serve not working

### ISSUE THREAD

**Issue by aaroncalderon** [yeoman/generator-angular#1268]
After installing the generator and choosing gulp, I ran `gulp serve`. However, the app did not load any javascript or css from bower components.

I tried to look into the gulpfile.js but was unable to figure out what went wrong.

I am using: 
Windows 7 32bit
node v4.1.1
npm v2.14.4
yo v1.5.0

Then I tried it again with all defaults on the yo prompts. Output is as follows:  

```
Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Gulp (experimental) instead of Grunt? yes
? Would you like to use Sass (with Compass)? no
? Would you like to include Bootstrap? Yes
? Would you like to use the Sass version of Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-route.js, angular-sanitize.js, angular-touch.j
```

Grunt works dough.

Thanks

**Comment by karthilxg** [comment]
I'm facing the same issue, basically `wiredep` not injecting the bower components to the `index.html`

**Comment by mateomrqz** [comment]
Same issue in Mac OS X both Gulp / Grunt -- Any solutions?

**Comment by jookes** [comment]
There is a pull request (#1247) waiting that should fix the problems you are experiencing, you could try and pull it yourself and see if that resolves your issues.

**Comment by geoguide** [comment]
Did not fix it for me. Looks like I'm reinstalling with grunt.

**Comment by vishalkrv** [comment]
Gulp start:client starts the server for me however the wiredep feature is not working for me
